### ISSUE TITLE
Documentation - invalid dao packages

### ISSUE THREAD

**Issue by dos65** [dnvriend/akka-persistence#1]
Configuration example contains dao definition with incorrect package
As example:
`dao = "akka.persistence.jdbc.query.dao.ByteArrayReadJournalDao"`

which should be in latest version:
`dao = "akka.persistence.jdbc.dao.bytea.readjournal.ByteArrayReadJournalDao"`

**Comment by dnvriend** [comment]
Thanks for the PR and mention, but I'm afraid the original dao definitions are correct.

**Comment by dos65** [comment]
Sorry, it seems that i used oldest version.
There is another place with incorrect dao package https://dnvriend.github.io/akka-persistence/jdbc.html#custom-dao-implementation , with `bytea` package
