### ISSUE TITLE
Circuit Breaker time out within Docker

### ISSUE THREAD

**Issue by joseblas** [dnvriend/akka-persistence#4]
Hi,

 I have a Play Scala App within Docker. When is run I get this error:

Persistence failure when replaying events for persistenceId [persistent-actor]. Last known sequence number [0]
akka.pattern.CircuitBreaker$$anon$1: Circuit Breaker Timed out.

**Comment by dnvriend** [comment]
Hi, do you have any more information why the circuit breaker timed out?

**Comment by joseblas** [comment]
My bad Dennis,
  it's an internal issue with the configuration.
